### ISSUE TITLE
关于同类型任务合并

### ISSUE THREAD

**Issue by white-wolf-tech** [yule-BUAA/MergeLLM#1]
作者您好？
看了下这个方法，整体很不错。
有个问题：有个任务，我训练了5个epoch，每个epoch都有checkpoint，我想把这个五个checkpoint合并起来，以提升泛化性。是不是不能使用widen的方法？
直观感觉，应该使用DARE，做平均的方式应该更好。

**Comment by yule-BUAA** [comment]
嗨，

对从我们目前的实验结果看，WIDEN更适合于合并参数变化存在差异的多个模型。对于每个epoch的checkpoint，它们之间的参数变化应该很小，感觉直接做平均就可以。当然WIDEN也能在这种情况下使用，只是效果还有待验证。

**Comment by white-wolf-tech** [comment]
> 嗨，
> 
> 对从我们目前的实验结果看，WIDEN更适合于合并参数变化存在差异的多个模型。对于每个epoch的checkpoint，它们之间的参数变化应该很小，感觉直接做平均就可以。当然WIDEN也能在这种情况下使用，只是效果还有待验证。

感谢。感谢。
